// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actions.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action struct {
	AcID        string `protobuf:"bytes,1,opt,name=AcID,json=acID,proto3" json:"AcID,omitempty"`
	CpID        string `protobuf:"bytes,2,opt,name=CpID,json=cpID,proto3" json:"CpID,omitempty"`
	Action      string `protobuf:"bytes,3,opt,name=Action,json=action,proto3" json:"Action,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	// Datastore Key
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetAcID() string {
	if m != nil {
		return m.AcID
	}
	return ""
}

func (m *Action) GetCpID() string {
	if m != nil {
		return m.CpID
	}
	return ""
}

func (m *Action) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Action) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Action) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Action)(nil), "proto.Action")
}

func init() { proto.RegisterFile("actions.proto", fileDescriptor_eeb49063df94c2b8) }

var fileDescriptor_eeb49063df94c2b8 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x0d, 0x8c,
	0x5c, 0x6c, 0x8e, 0x60, 0x09, 0x21, 0x21, 0x2e, 0x16, 0xc7, 0x64, 0x4f, 0x17, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x96, 0xc4, 0x64, 0x4f, 0x17, 0x90, 0x98, 0x73, 0x81, 0xa7, 0x8b, 0x04,
	0x13, 0x44, 0x2c, 0xb9, 0xc0, 0xd3, 0x45, 0x48, 0x0c, 0xa6, 0x43, 0x82, 0x19, 0x2c, 0xca, 0x06,
	0x31, 0x58, 0x48, 0x81, 0x8b, 0xdb, 0x25, 0xb5, 0x38, 0xb9, 0x28, 0xb3, 0x00, 0x2c, 0xc9, 0x02,
	0x96, 0xe4, 0x4e, 0x41, 0x08, 0x09, 0x89, 0x70, 0xb1, 0x7a, 0xa7, 0x56, 0x7a, 0xba, 0x48, 0xa4,
	0x28, 0x30, 0x6a, 0x08, 0x05, 0xb1, 0x66, 0x83, 0x38, 0x49, 0x6c, 0x60, 0x97, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xbf, 0x4b, 0xf9, 0x96, 0xa1, 0x00, 0x00, 0x00,
}
