// Code generated by protoc-gen-go. DO NOT EDIT.
// source: callpoints.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Callpoint struct {
	// Common Types
	CpID  string `protobuf:"bytes,1,opt,name=CpID,json=cpID,proto3" json:"CpID,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=Label,json=label,proto3" json:"Label,omitempty"`
	Type  int32  `protobuf:"varint,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Icon  string `protobuf:"bytes,4,opt,name=Icon,json=icon,proto3" json:"Icon,omitempty"`
	// Specific types
	AbsAddress string `protobuf:"bytes,20,opt,name=AbsAddress,json=absAddress,proto3" json:"AbsAddress,omitempty"`
	Priority   int32  `protobuf:"varint,21,opt,name=Priority,json=priority,proto3" json:"Priority,omitempty"`
	// More Generic Types
	Description string `protobuf:"bytes,40,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	// Datastore Key
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Callpoint) Reset()         { *m = Callpoint{} }
func (m *Callpoint) String() string { return proto.CompactTextString(m) }
func (*Callpoint) ProtoMessage()    {}
func (*Callpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0966319cfc7f9517, []int{0}
}

func (m *Callpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Callpoint.Unmarshal(m, b)
}
func (m *Callpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Callpoint.Marshal(b, m, deterministic)
}
func (m *Callpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Callpoint.Merge(m, src)
}
func (m *Callpoint) XXX_Size() int {
	return xxx_messageInfo_Callpoint.Size(m)
}
func (m *Callpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Callpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Callpoint proto.InternalMessageInfo

func (m *Callpoint) GetCpID() string {
	if m != nil {
		return m.CpID
	}
	return ""
}

func (m *Callpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Callpoint) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Callpoint) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Callpoint) GetAbsAddress() string {
	if m != nil {
		return m.AbsAddress
	}
	return ""
}

func (m *Callpoint) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Callpoint) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Callpoint) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Callpoint)(nil), "proto.Callpoint")
}

func init() { proto.RegisterFile("callpoints.proto", fileDescriptor_0966319cfc7f9517) }

var fileDescriptor_0966319cfc7f9517 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x89, 0x6e, 0xe4, 0x6e, 0xae, 0x91, 0xe1, 0x84, 0xc1, 0x42, 0x16, 0xab, 0xad, 0x6c,
	0x7c, 0x82, 0x63, 0xb7, 0x09, 0x5a, 0xc8, 0xe2, 0x0b, 0xec, 0x26, 0x29, 0x82, 0x21, 0x19, 0x92,
	0x34, 0x79, 0x4c, 0xdf, 0x48, 0x12, 0xff, 0x55, 0xe1, 0xf7, 0xfb, 0xf2, 0x0d, 0x33, 0x70, 0xab,
	0x37, 0xef, 0x39, 0xba, 0x50, 0xf2, 0x13, 0xa7, 0x58, 0x22, 0xca, 0xfe, 0x3c, 0x7e, 0x0a, 0x38,
	0xce, 0xbf, 0x19, 0x22, 0x0c, 0x33, 0xab, 0x85, 0xc4, 0x28, 0xa6, 0xe3, 0x3a, 0x68, 0x56, 0x0b,
	0x9e, 0x41, 0xbe, 0x6e, 0xbb, 0xf5, 0x74, 0xd5, 0xa5, 0xf4, 0x0d, 0xda, 0xcf, 0xf7, 0xca, 0x96,
	0xae, 0x47, 0x31, 0xc9, 0x75, 0x28, 0x95, 0x6d, 0x73, 0x4a, 0xc7, 0x40, 0xc3, 0x77, 0xdb, 0xe9,
	0x18, 0xf0, 0x01, 0xe0, 0xb2, 0xe7, 0x8b, 0x31, 0xc9, 0xe6, 0x4c, 0xe7, 0x9e, 0xc0, 0xf6, 0x67,
	0xf0, 0x1e, 0x0e, 0x6f, 0xc9, 0xc5, 0xe4, 0x4a, 0xa5, 0xbb, 0x3e, 0xeb, 0xc0, 0x3f, 0x8c, 0x23,
	0x9c, 0x16, 0x9b, 0x75, 0x72, 0x5c, 0x5c, 0x0c, 0x34, 0xf5, 0xf2, 0xc9, 0xfc, 0xab, 0xb6, 0xdb,
	0x8b, 0xad, 0x6a, 0x21, 0x33, 0x8a, 0x09, 0x57, 0xf9, 0xd1, 0x60, 0xbf, 0xe9, 0xa7, 0x3d, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xce, 0xd5, 0xb7, 0xf5, 0x00, 0x00, 0x00,
}
