// Code generated by protoc-gen-go. DO NOT EDIT.
// source: callpoints.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Callpoint struct {
	CpID                 string   `protobuf:"bytes,1,opt,name=CpID,json=cpID,proto3" json:"CpID,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=Label,json=label,proto3" json:"Label,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=Icon,json=icon,proto3" json:"Icon,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Priority             int32    `protobuf:"varint,6,opt,name=Priority,json=priority,proto3" json:"Priority,omitempty"`
	AbsAddress           string   `protobuf:"bytes,7,opt,name=AbsAddress,json=absAddress,proto3" json:"AbsAddress,omitempty"`
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Callpoint) Reset()         { *m = Callpoint{} }
func (m *Callpoint) String() string { return proto.CompactTextString(m) }
func (*Callpoint) ProtoMessage()    {}
func (*Callpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0966319cfc7f9517, []int{0}
}

func (m *Callpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Callpoint.Unmarshal(m, b)
}
func (m *Callpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Callpoint.Marshal(b, m, deterministic)
}
func (m *Callpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Callpoint.Merge(m, src)
}
func (m *Callpoint) XXX_Size() int {
	return xxx_messageInfo_Callpoint.Size(m)
}
func (m *Callpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Callpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Callpoint proto.InternalMessageInfo

func (m *Callpoint) GetCpID() string {
	if m != nil {
		return m.CpID
	}
	return ""
}

func (m *Callpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Callpoint) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Callpoint) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Callpoint) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Callpoint) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Callpoint) GetAbsAddress() string {
	if m != nil {
		return m.AbsAddress
	}
	return ""
}

func (m *Callpoint) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Callpoint)(nil), "proto.Callpoint")
}

func init() { proto.RegisterFile("callpoints.proto", fileDescriptor_0966319cfc7f9517) }

var fileDescriptor_0966319cfc7f9517 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbf, 0x4e, 0x04, 0x21,
	0x10, 0xc6, 0x83, 0x2e, 0xe7, 0xdd, 0x5c, 0x63, 0x26, 0x16, 0x13, 0x0b, 0xb3, 0xb1, 0xda, 0xca,
	0xc6, 0x27, 0xb8, 0xec, 0x36, 0x44, 0x0b, 0xb3, 0xf1, 0x05, 0x76, 0x81, 0x82, 0x48, 0x60, 0x02,
	0x34, 0x3c, 0xa6, 0x6f, 0x64, 0xc0, 0x7f, 0x15, 0xf9, 0xfd, 0x3e, 0xbe, 0xc9, 0x0c, 0xdc, 0xea,
	0xcd, 0x7b, 0x8e, 0x2e, 0x94, 0xfc, 0xc4, 0x29, 0x96, 0x88, 0xb2, 0x3f, 0x8f, 0x9f, 0x02, 0x4e,
	0xf3, 0x6f, 0x86, 0x08, 0xc3, 0xcc, 0x6a, 0x21, 0x31, 0x8a, 0xe9, 0xb4, 0x0e, 0x9a, 0xd5, 0x82,
	0x77, 0x20, 0x5f, 0xb7, 0xdd, 0x7a, 0xba, 0xea, 0x52, 0xfa, 0x06, 0xed, 0xe7, 0x7b, 0x65, 0x4b,
	0xd7, 0xa3, 0x98, 0xe4, 0x3a, 0x94, 0xca, 0xb6, 0x39, 0xa5, 0x63, 0xa0, 0xe1, 0xbb, 0xed, 0x74,
	0x0c, 0x38, 0xc2, 0x79, 0xb1, 0x59, 0x27, 0xc7, 0xc5, 0xc5, 0x40, 0xb2, 0x47, 0x67, 0xf3, 0xaf,
	0xf0, 0x1e, 0x8e, 0x6f, 0xc9, 0xc5, 0xe4, 0x4a, 0xa5, 0x43, 0x9f, 0x76, 0xe4, 0x1f, 0xc6, 0x07,
	0x80, 0xcb, 0x9e, 0x2f, 0xc6, 0x24, 0x9b, 0x33, 0xdd, 0xf4, 0x32, 0x6c, 0x7f, 0xa6, 0xed, 0xf6,
	0x62, 0xab, 0x5a, 0xc8, 0x8c, 0x62, 0xc2, 0x55, 0x7e, 0x34, 0xd8, 0x0f, 0xfd, 0xb4, 0xe7, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x22, 0x01, 0x2e, 0xf5, 0x00, 0x00, 0x00,
}
