// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonSetting struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonSetting) Reset()         { *m = CommonSetting{} }
func (m *CommonSetting) String() string { return proto.CompactTextString(m) }
func (*CommonSetting) ProtoMessage()    {}
func (*CommonSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *CommonSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonSetting.Unmarshal(m, b)
}
func (m *CommonSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonSetting.Marshal(b, m, deterministic)
}
func (m *CommonSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonSetting.Merge(m, src)
}
func (m *CommonSetting) XXX_Size() int {
	return xxx_messageInfo_CommonSetting.Size(m)
}
func (m *CommonSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonSetting.DiscardUnknown(m)
}

var xxx_messageInfo_CommonSetting proto.InternalMessageInfo

func (m *CommonSetting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommonSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CommonSetting) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonSetting)(nil), "proto.CommonSetting")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xbe, 0x5c, 0xbc,
	0xce, 0x60, 0xe1, 0xe0, 0xd4, 0x92, 0x92, 0xcc, 0xbc, 0x74, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4,
	0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x21, 0x11,
	0x2e, 0xd6, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0, 0x20, 0x6b, 0x19, 0x88, 0x03, 0x52,
	0x19, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0x0c, 0x51, 0x59, 0x52, 0x59, 0x90, 0x9a, 0xc4, 0x06, 0x36,
	0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x32, 0xa9, 0xa2, 0x81, 0x6c, 0x00, 0x00, 0x00,
}
