// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devices.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceSetting struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceSetting) Reset()         { *m = DeviceSetting{} }
func (m *DeviceSetting) String() string { return proto.CompactTextString(m) }
func (*DeviceSetting) ProtoMessage()    {}
func (*DeviceSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{0}
}

func (m *DeviceSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSetting.Unmarshal(m, b)
}
func (m *DeviceSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSetting.Marshal(b, m, deterministic)
}
func (m *DeviceSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSetting.Merge(m, src)
}
func (m *DeviceSetting) XXX_Size() int {
	return xxx_messageInfo_DeviceSetting.Size(m)
}
func (m *DeviceSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSetting.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSetting proto.InternalMessageInfo

func (m *DeviceSetting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DeviceSetting) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Device struct {
	// Common Types
	DvID  string `protobuf:"bytes,1,opt,name=DvID,json=dvID,proto3" json:"DvID,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=Label,json=label,proto3" json:"Label,omitempty"`
	Type  int32  `protobuf:"varint,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Icon  string `protobuf:"bytes,4,opt,name=Icon,json=icon,proto3" json:"Icon,omitempty"`
	// Specific types
	Priority    int32            `protobuf:"varint,20,opt,name=Priority,json=priority,proto3" json:"Priority,omitempty"`
	IsTwoWay    bool             `protobuf:"varint,21,opt,name=IsTwoWay,json=isTwoWay,proto3" json:"IsTwoWay,omitempty"`
	Category    string           `protobuf:"bytes,22,opt,name=Category,json=category,proto3" json:"Category,omitempty"`
	Destination string           `protobuf:"bytes,23,opt,name=Destination,json=destination,proto3" json:"Destination,omitempty"`
	Settings    []*DeviceSetting `protobuf:"bytes,24,rep,name=Settings,json=settings,proto3" json:"Settings,omitempty"`
	// More Generic Types
	Description string `protobuf:"bytes,40,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	// Datastore Key
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDvID() string {
	if m != nil {
		return m.DvID
	}
	return ""
}

func (m *Device) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Device) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Device) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Device) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Device) GetIsTwoWay() bool {
	if m != nil {
		return m.IsTwoWay
	}
	return false
}

func (m *Device) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Device) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Device) GetSettings() []*DeviceSetting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Device) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Device) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*DeviceSetting)(nil), "proto.DeviceSetting")
	proto.RegisterType((*Device)(nil), "proto.Device")
}

func init() { proto.RegisterFile("devices.proto", fileDescriptor_6d27ec3f2c0e2043) }

var fileDescriptor_6d27ec3f2c0e2043 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xe9, 0xcc, 0x74, 0x88, 0x29, 0xb3, 0x09, 0x55, 0x2f, 0xae, 0xca, 0xac, 0xba, 0x1a,
	0x44, 0x1f, 0xc1, 0x6c, 0x8a, 0x3f, 0x48, 0x1d, 0x74, 0x9d, 0x69, 0x2f, 0x43, 0xb0, 0x93, 0x94,
	0x36, 0x56, 0xf2, 0x6a, 0x3e, 0x9d, 0xe4, 0xa7, 0xca, 0xac, 0xc2, 0x77, 0xee, 0xc9, 0xb7, 0x38,
	0x74, 0xd3, 0xe2, 0x24, 0x1b, 0x1c, 0x77, 0xfd, 0xa0, 0x8d, 0x66, 0xa9, 0x7f, 0xb6, 0xcf, 0x74,
	0xc3, 0x7d, 0xfe, 0x86, 0xc6, 0x48, 0x75, 0x64, 0x8c, 0xae, 0x5e, 0xc4, 0x09, 0x21, 0x29, 0x92,
	0xf2, 0xa2, 0x5e, 0x29, 0x71, 0x42, 0x96, 0xd3, 0xf4, 0x5d, 0x74, 0x5f, 0x08, 0x0b, 0x1f, 0xa6,
	0x93, 0x03, 0xd7, 0xdc, 0xdb, 0x1e, 0x61, 0x19, 0x9a, 0xc6, 0xf6, 0xb8, 0xfd, 0x59, 0xd0, 0x75,
	0xf0, 0xb9, 0x33, 0x9f, 0x2a, 0x3e, 0x8b, 0xda, 0xa9, 0xe2, 0x4e, 0xf4, 0x24, 0x0e, 0xd8, 0xcd,
	0xa2, 0xce, 0xc1, 0x99, 0x28, 0x0d, 0x22, 0x97, 0x55, 0x8d, 0x56, 0xb0, 0x0a, 0xbf, 0x65, 0xa3,
	0x15, 0xbb, 0xa1, 0xe4, 0x75, 0x90, 0x7a, 0x90, 0xc6, 0x42, 0xee, 0xbb, 0xa4, 0x8f, 0xec, 0x6e,
	0xd5, 0xb8, 0xff, 0xd6, 0x1f, 0xc2, 0xc2, 0x65, 0x91, 0x94, 0xa4, 0x26, 0x32, 0xb2, 0xbb, 0x3d,
	0x08, 0x83, 0x47, 0x3d, 0x58, 0xb8, 0xf2, 0x3e, 0xd2, 0x44, 0x66, 0x05, 0xcd, 0x38, 0x8e, 0x46,
	0x2a, 0x61, 0xa4, 0x56, 0x70, 0xed, 0xcf, 0x59, 0xfb, 0x1f, 0xb1, 0x5b, 0x4a, 0xe2, 0x36, 0x23,
	0x40, 0xb1, 0x2c, 0xb3, 0xbb, 0x3c, 0x4c, 0xb8, 0x3b, 0x1b, 0xae, 0x26, 0x63, 0x6c, 0x45, 0x67,
	0x33, 0xc8, 0xde, 0x3b, 0xcb, 0x3f, 0xe7, 0x1c, 0xb9, 0x1d, 0x1e, 0xd1, 0x56, 0x1c, 0xda, 0x22,
	0x29, 0x59, 0x9d, 0x7e, 0x3a, 0x38, 0xac, 0xbd, 0xf6, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x97,
	0x7c, 0xcf, 0x3f, 0xaa, 0x01, 0x00, 0x00,
}
