// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Notification struct {
	NtID                 string   `protobuf:"bytes,1,opt,name=NtID,json=ntID,proto3" json:"NtID,omitempty"`
	EvID                 string   `protobuf:"bytes,2,opt,name=EvID,json=evID,proto3" json:"EvID,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=Priority,json=priority,proto3" json:"Priority,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,json=category,proto3" json:"Category,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	ResponseTitle        string   `protobuf:"bytes,7,opt,name=ResponseTitle,json=responseTitle,proto3" json:"ResponseTitle,omitempty"`
	Options              string   `protobuf:"bytes,8,opt,name=Options,json=options,proto3" json:"Options,omitempty"`
	EvSubType            string   `protobuf:"bytes,9,opt,name=EvSubType,json=evSubType,proto3" json:"EvSubType,omitempty"`
	AbsAddress           string   `protobuf:"bytes,10,opt,name=AbsAddress,json=absAddress,proto3" json:"AbsAddress,omitempty"`
	EvDescription        string   `protobuf:"bytes,11,opt,name=EvDescription,json=evDescription,proto3" json:"EvDescription,omitempty"`
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNtID() string {
	if m != nil {
		return m.NtID
	}
	return ""
}

func (m *Notification) GetEvID() string {
	if m != nil {
		return m.EvID
	}
	return ""
}

func (m *Notification) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Notification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notification) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Notification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Notification) GetResponseTitle() string {
	if m != nil {
		return m.ResponseTitle
	}
	return ""
}

func (m *Notification) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *Notification) GetEvSubType() string {
	if m != nil {
		return m.EvSubType
	}
	return ""
}

func (m *Notification) GetAbsAddress() string {
	if m != nil {
		return m.AbsAddress
	}
	return ""
}

func (m *Notification) GetEvDescription() string {
	if m != nil {
		return m.EvDescription
	}
	return ""
}

func (m *Notification) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Notification)(nil), "proto.Notification")
}

func init() { proto.RegisterFile("notifications.proto", fileDescriptor_fbc3de4cce73c76f) }

var fileDescriptor_fbc3de4cce73c76f = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xe9, 0x7c, 0xd3, 0x69, 0x7b, 0xfb, 0xcd, 0xe6, 0xea, 0xe2, 0x22, 0x22, 0x45, 0x5c,
	0x74, 0xe5, 0xc6, 0x27, 0x18, 0x4c, 0x17, 0x45, 0x1c, 0xa5, 0xce, 0x0b, 0xf4, 0xcf, 0x75, 0x08,
	0x6a, 0x53, 0x92, 0x58, 0xe8, 0xfb, 0xfa, 0x20, 0x92, 0x74, 0xd4, 0xae, 0xc2, 0xf9, 0xfd, 0x38,
	0x39, 0x21, 0x70, 0xd6, 0x2b, 0x2b, 0x5f, 0x65, 0x5b, 0x5b, 0xa9, 0x7a, 0x73, 0x3b, 0x68, 0x65,
	0x15, 0x86, 0xfe, 0xb8, 0xfe, 0x5a, 0xc1, 0xff, 0xfd, 0x42, 0x23, 0xc2, 0x7a, 0x6f, 0x4b, 0x41,
	0x41, 0x16, 0xe4, 0x49, 0xb5, 0xee, 0x6d, 0x29, 0x1c, 0x2b, 0xc6, 0x52, 0xd0, 0x6a, 0x66, 0x3c,
	0x96, 0x02, 0x2f, 0x20, 0x7e, 0xd6, 0x52, 0x69, 0x69, 0x27, 0xfa, 0x97, 0x05, 0x79, 0x58, 0xc5,
	0xc3, 0x29, 0x3b, 0x77, 0x5f, 0x5b, 0x3e, 0x2a, 0x3d, 0xd1, 0xda, 0x77, 0xe2, 0xf6, 0x94, 0x31,
	0x83, 0x54, 0xb0, 0x69, 0xb5, 0x1c, 0xdc, 0x1c, 0x85, 0x5e, 0xa7, 0xdd, 0x1f, 0x42, 0x82, 0xe8,
	0x91, 0x8d, 0xa9, 0x8f, 0x4c, 0x1b, 0x6f, 0xa3, 0x8f, 0x39, 0xe2, 0x0d, 0x6c, 0x2b, 0x36, 0x83,
	0xea, 0x0d, 0x1f, 0xa4, 0x7d, 0x67, 0x8a, 0xbc, 0xdf, 0xea, 0x25, 0x74, 0xfd, 0x27, 0x7f, 0x93,
	0xa1, 0x78, 0xee, 0xab, 0x39, 0xe2, 0x25, 0x24, 0xc5, 0xf8, 0xf2, 0xd9, 0x1c, 0xa6, 0x81, 0x29,
	0xf1, 0x2e, 0xe1, 0x1f, 0x80, 0x57, 0x00, 0xbb, 0xc6, 0xec, 0xba, 0x4e, 0xb3, 0x31, 0x04, 0x5e,
	0x43, 0xfd, 0x4b, 0xdc, 0x7a, 0x31, 0x2e, 0xdf, 0x9e, 0xce, 0xeb, 0xbc, 0x84, 0x78, 0x0e, 0xe1,
	0x03, 0x4f, 0xa5, 0xa0, 0x2e, 0x0b, 0x72, 0xac, 0xc2, 0x37, 0x17, 0x9a, 0x8d, 0xff, 0xed, 0xbb,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x72, 0xb1, 0x5a, 0x8b, 0x01, 0x00, 0x00,
}
