// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Notification struct {
	NtID          string `protobuf:"bytes,1,opt,name=NtID,json=ntID,proto3" json:"NtID,omitempty"`
	AcID          string `protobuf:"bytes,2,opt,name=AcID,json=acID,proto3" json:"AcID,omitempty"`
	Priority      int32  `protobuf:"varint,3,opt,name=Priority,json=priority,proto3" json:"Priority,omitempty"`
	Category      string `protobuf:"bytes,4,opt,name=Category,json=category,proto3" json:"Category,omitempty"`
	Destination   string `protobuf:"bytes,5,opt,name=Destination,json=destination,proto3" json:"Destination,omitempty"`
	Message       string `protobuf:"bytes,6,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	ResponseTitle string `protobuf:"bytes,7,opt,name=ResponseTitle,json=responseTitle,proto3" json:"ResponseTitle,omitempty"`
	Options       string `protobuf:"bytes,8,opt,name=Options,json=options,proto3" json:"Options,omitempty"`
	// extra information to fill events
	CpID                 string   `protobuf:"bytes,9,opt,name=cpID,proto3" json:"cpID,omitempty"`
	DvID                 string   `protobuf:"bytes,10,opt,name=dvID,proto3" json:"dvID,omitempty"`
	KeyID                int64    `protobuf:"zigzag64,100,opt,name=KeyID,json=keyID,proto3" json:"KeyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNtID() string {
	if m != nil {
		return m.NtID
	}
	return ""
}

func (m *Notification) GetAcID() string {
	if m != nil {
		return m.AcID
	}
	return ""
}

func (m *Notification) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Notification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notification) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Notification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Notification) GetResponseTitle() string {
	if m != nil {
		return m.ResponseTitle
	}
	return ""
}

func (m *Notification) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *Notification) GetCpID() string {
	if m != nil {
		return m.CpID
	}
	return ""
}

func (m *Notification) GetDvID() string {
	if m != nil {
		return m.DvID
	}
	return ""
}

func (m *Notification) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func init() {
	proto.RegisterType((*Notification)(nil), "proto.Notification")
}

func init() { proto.RegisterFile("notifications.proto", fileDescriptor_fbc3de4cce73c76f) }

var fileDescriptor_fbc3de4cce73c76f = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0xda, 0x6e, 0xbb, 0xb3, 0xee, 0x65, 0xf4, 0x30, 0x78, 0x2a, 0xe2, 0xa1, 0x27,
	0x2f, 0x3e, 0x81, 0x98, 0x4b, 0x10, 0x57, 0x29, 0xbe, 0x40, 0x4d, 0xe3, 0x12, 0xd4, 0x24, 0x24,
	0x83, 0xd0, 0x37, 0xf2, 0x31, 0x25, 0xc9, 0xc2, 0xee, 0xa9, 0xf3, 0x7f, 0x1f, 0x3f, 0xe5, 0x0f,
	0x5c, 0x59, 0xc7, 0xe6, 0xd3, 0xa8, 0x89, 0x8d, 0xb3, 0xf1, 0xde, 0x07, 0xc7, 0x0e, 0x9b, 0xfc,
	0xb9, 0xfd, 0x5b, 0xc1, 0xe5, 0xfe, 0x4c, 0x23, 0x42, 0xbd, 0x67, 0x29, 0xa8, 0xea, 0xab, 0x61,
	0x33, 0xd6, 0x96, 0xa5, 0x48, 0xec, 0x51, 0x49, 0x41, 0xab, 0xc2, 0x26, 0x25, 0x05, 0xde, 0x40,
	0xf7, 0x16, 0x8c, 0x0b, 0x86, 0x17, 0xba, 0xe8, 0xab, 0xa1, 0x19, 0x3b, 0x7f, 0xcc, 0xc9, 0x3d,
	0x4d, 0xac, 0x0f, 0x2e, 0x2c, 0x54, 0xe7, 0x4e, 0xa7, 0x8e, 0x19, 0x7b, 0xd8, 0x0a, 0x1d, 0xd9,
	0xd8, 0xfc, 0x3b, 0x6a, 0xb2, 0xde, 0xce, 0x27, 0x84, 0x04, 0xed, 0x8b, 0x8e, 0x71, 0x3a, 0x68,
	0x5a, 0x67, 0xdb, 0xfe, 0x94, 0x88, 0x77, 0xb0, 0x1b, 0x75, 0xf4, 0xce, 0x46, 0xfd, 0x6e, 0xf8,
	0x5b, 0x53, 0x9b, 0xfd, 0x2e, 0x9c, 0xc3, 0xd4, 0x7f, 0xf5, 0x79, 0x2a, 0x75, 0xa5, 0xef, 0x4a,
	0x4c, 0x3b, 0x94, 0x97, 0x82, 0x36, 0x65, 0x47, 0xba, 0x13, 0x9b, 0x7f, 0xa5, 0x20, 0x28, 0x2c,
	0xdd, 0x78, 0x0d, 0xcd, 0xb3, 0x5e, 0xa4, 0xa0, 0xb9, 0xaf, 0x06, 0x1c, 0x9b, 0xaf, 0x14, 0x3e,
	0xd6, 0xf9, 0xc5, 0x1e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xec, 0x0d, 0x86, 0xa1, 0x4f, 0x01,
	0x00, 0x00,
}
